### ISSUE TITLE
Question:  Consuming Web Service from other application

### ISSUE THREAD

**Issue by zachariahyoung** [olivergierke/spring-restbucks#42]
In the past, with SOAP webservice a wsdl would be exposed for another application to be able to generate the classes to create a web service client.  Since this is not a SOAP service, it is a REST service how could another developer quickly create a client application using this REST service.  The calling application could be in .net or java.

It seems like you would want to allow for some reuse and package up the entity class in a separate library.

**Comment by gregturn** [comment]
SOAP is an RPC style interface. That's why, with a spec in hand, you can autogenerate clients to talk to the endpoints. In exchange for such easy-to-generate clients, the API becomes brittle when you attempt to make changes. REST works from a different perspective that doesn't lock you into such fixed contracts.

If you read up on Spring HATEOAS's [Traverson](http://docs.spring.io/spring-hateoas/docs/current/reference/html/#client.traverson) module, it introduces the concept of navigating a set of relationships. 

Spring Data REST, the core tech underneath this demo app, also comes with metadata ([ALPS](http://docs.spring.io/spring-data/rest/docs/2.4.0.RELEASE/reference/html/#metadata.alps) and [JSON Schema](http://docs.spring.io/spring-data/rest/docs/2.4.0.RELEASE/reference/html/#metadata.json-schema)) to help you understand the format of things as well as the available transitions.

The navigation combined with the metadata empowers you to build UIs where you give the client the info and controls to navigate your API, something completely different from an RPC-style SOAP solution.

For another example, check out https://spring.io/blog/2015/09/15/react-js-and-spring-data-rest-part-2-hypermedia

**Comment by zachariahyoung** [comment]
I get the feeling that REST APIs are build for UI application only.  Greg I have read over part 2 already of your demo application and that's what has got me a bit puzzled.  It's been hard to explain to developer how a non-RPC style API works.

**Comment by gregturn** [comment]
The go-to metaphor I use is imagine your app/client/UI is a browser. The browser has been phenomenally successful because the the medium it operates over uses links. The rate websites evolve is much faster than HTML and browsers have to evolve. Browsers don't require updates everything a web site changes, or every time the connection changes. The concept of REST by Roy Fielding was to carry this flexible, navigable concept and carry it to APIs. Instead of hitching apps to RPC-like connections, use links and relationships.

When a UI is involved, then yes, there is an easy way to put links onto the page, like my demo. It really shines. But when you are hitching services together, it is easy to explore the service (curl anyone?). Even if you don't encode that into the actual working code, such discoverability cannot be understated. You can use tools like retrofit and feign to hard code these fixed paths to interface definitions.

In the end, by embracing links, you set things up in the future for letting such links ultimately service the UI, because most things end up in the user's space, right? If you never pick up links with stuff like HAL, then I feel you are forever doomed to the barebones of RPC.

**Comment by zachariahyoung** [comment]
So if I have a .Net application and I want to call a java Restful webservice what's your recommendation?  Would you have to build native .net library?

**Comment by gregturn** [comment]
The author of the HAL spec has gathered [this listing](https://github.com/mikekelly/hal_specification/wiki/Libraries) of libraries. You could investigate the ones listed under C#. I have no experience with HAL libraries beyond Java and JavaScript.

**Comment by olivergierke** [comment]
I suggest you move that question to StackOverflow. The tracker here is used to keep track of issues with the RESTBucks implementation, general questions.
